version: '3.6'
services:
  db:
    image: postgres
    container_name: LogDoc_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "logdoc"
      POSTGRES_USER: "logdoc"
      POSTGRES_PASSWORD: "logdoc"
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: LogDoc_clickhouse
    restart: on-failure
    environment:
      CLICKHOUSE_DB: "logdoc"
      CLICKHOUSE_USER: "logdoc"
      CLICKHOUSE_PASSWORD: "logdoc"
      CLICKHOUSE_HTTP_PORT: ${CLICKHOUSE_HTTP_PORT} # 8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./configs/clickhouse_server_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./logs/clickhouse:/var/log/clickhouse-server
    network_mode: host
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${CLICKHOUSE_HTTP_PORT}/ping || exit 1
      interval: 3s
      timeout: 10s
      retries: 5

volumes:
  logdoc_db:
  logdoc_clickhouse:
