FROM openjdk:11-jdk-slim

COPY ./community .

ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD

ARG CLICKHOUSE_HOST
ARG CLICKHOUSE_PORT
ARG CLICKHOUSE_DB
ARG CLICKHOUSE_USER
ARG CLICKHOUSE_PASSWORD

ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ENV CLICKHOUSE_HOST=$CLICKHOUSE_HOST
ENV CLICKHOUSE_PORT=$CLICKHOUSE_PORT
ENV CLICKHOUSE_DB=$CLICKHOUSE_DB
ENV CLICKHOUSE_USER=$CLICKHOUSE_USER
ENV CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD

CMD "./bin/community"