version: '3.6'
services:
  db:
    image: postgres
    container_name: ld_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "logdoc"
      POSTGRES_USER: "logdoc"
      POSTGRES_PASSWORD: "logdoc"
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U logdoc -d logdoc" ]
      interval: 3s
      timeout: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: ld_click
    restart: on-failure
    environment:
      CLICKHOUSE_DB: "logdoc"
      CLICKHOUSE_USER: "logdoc"
      CLICKHOUSE_PASSWORD: "logdoc"
      CLICKHOUSE_HTTP_PORT: ${CLICKHOUSE_HTTP_PORT} # 8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./configs/clickhouse_server_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./logs/clickhouse:/var/log/clickhouse-server
    network_mode: host
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${CLICKHOUSE_HTTP_PORT}/ping || exit 1
      interval: 3s
      timeout: 10s
      retries: 5

  logdoc:
    image: logdoc/community:latest
    container_name: ld_core
    depends_on:
      clickhouse:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      PG_PORT: ${POSTGRES_PORT}
      CLICK_PORT: ${CLICKHOUSE_HTTP_PORT}
      LOGDOC_PORT: ${LOGDOC_HOST_PORT}
    volumes:
      - ./data/logdoc:/logdoc/conf/keys
      - ./logs/logdoc:/logdoc/logs
      - ./configs/logdoc_application_config.conf:/logdoc/conf/application.conf
      - ./configs/logdoc_logback_config.xml:/logdoc/conf/logback.xml
    restart: always
    network_mode: host

volumes:
  logdoc_db:
  logdoc_clickhouse:
  logdoc:
